name: Aprendiendo Github Actions
run-name: Estoy aprendiendo Github Actions!!!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "Hola mundo!"
      - name: Correr script
        run: index.php
